version: '3.8'
services:
    flask:
    # Путь до Dockerfile
        build: ./backend      
        image: backend-flask
    # Имя для создаваемого контейнера
        container_name: backend-flask
    # Создание переменных окружения в контейнере
        environment:
      # для отладки (при запуске в релиз убрать!)
        - FLASK_ENV=development
      ## Позволяет отслеживать процесс работы приложения в командной строке
        - PYTHONUNBUFFERED=True                   
      ##
    # Перезапускаем сервис в случае падения 
        restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
        volumes:
        - ./backend:/backend
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
        ports:
        - "5000:5000"

    
    nginx:
        image: nginx:latest
        container_name: edge-proxy
        tty: true
        ports:
        - "80:80"
        - "443:443"
        volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
